model:
  data_device: cuda
  model_path: ./ckpt/base_3dgs/llff/fern
  source_path: ./data/llff/fern

  resolution: 4

style:
  # stylized_model_path: output/TARGET_PATH
  style_image: ./data/style/style/0.jpg

  enable_stylize_densify: true
  enable_geometry_correction: true
  enable_nnfm_correction: true
  enable_color_transfer: true
  enable_geometry_correction: true
  enable_weighted: true
  enable_feature_enhancement: false
  enable_prior: false
  theta: 0

  lambda_content_loss: 0.005
  postpreprocess_iter: 400
  preprocess_iter: 400
  rounds: 10
  
  style_iter: 80
  correction_iter: 200

video:
  num_frames: 120