app:
  ip: 127.0.0.1
  need_log: false
  port: 6009
model:
  data_device: cuda
  model_path: /Datasets/radegs_0/llff/fortress
  source_path: /Datasets/preprocessed_data/llff/fortress

style:
  # stylized_model_path: output/2025-03-28_17-28-33

  enable_stylize_densify: true
  enable_geometry_correction: true
  enable_nnfm_correction: true
  enable_color_transfer: true
  enable_feature_enhancement: true
  enable_prior: false
  # densify: true
  gta_type: clip
  init_densification_downsample: 2
  init_densification_image_intervals: 10
  lambda_consistent_loss: 2
  lambda_content_loss: 0.005
  lambda_depth_loss: 0.01
  lambda_imgtv_loss: 0.02
  lambda_prior_loss: 2
  lambda_shape_loss: 0.1
  name: default
  no_grad: false
  postpreprocess_iter: 400
  preprocess_iter: 400
  enable_prior: false
  
  style_image: ./styles/black_white.jpg
  enable_geometry_correction: true

