model:
  data_device: cuda
  model_path: ./ckpt/base_3dgs/tnt/truck
  source_path: ./data/colmap/tnt/truck



style:
  # stylized_model_path: output/2025-03-28_17-28-33
  style_image: ./data/style/texture/banded_0005.jpg

  enable_stylize_densify: true
  enable_geometry_correction: true
  enable_nnfm_correction: true
  enable_color_transfer: true
  enable_geometry_correction: true
  enable_weighted: true
  enable_feature_enhancement: true
  enable_prior: true
  theta: 0

  lambda_content_loss: 0.0005
  postpreprocess_iter: 1000
  preprocess_iter: 1000
  rounds: 6

  style_iter: 400
  correction_iter: 1000
  
video:
  num_frames: 240